//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTWorkSafetyChecklist
    {
        public int HOT_ID { get; set; }
        public string S_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PermitNumber { get; set; }
        public string Agency { get; set; }
        public string Duration { get; set; }
        public string Location { get; set; }
        public string OtherObservations { get; set; }
        public string Remarks { get; set; }
        public string InspectorName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    }
}
