//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ApronAreaMaster
    {
        public int A_ID { get; set; }
        public Nullable<int> AG_ID { get; set; }
        public string Apron_Area { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
