//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SPOC
    {
        public int SPOC_ID { get; set; }
        public string SPOC_NAME { get; set; }
        public Nullable<int> SPOC_LEVEL { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public string SPOC_EmailId { get; set; }
    
        public virtual TBL_Departments TBL_Departments { get; set; }
    }
}
