//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Priority
    {
        public int PriorityID { get; set; }
        public string PName { get; set; }
        public Nullable<int> PeriodOfEscalation { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
