using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASMWebAPI.Models
{
    public class ApronChecklistProperty
    {
        public DateTime date { get; set; }
        public string inspectiontime { get; set; }
        public string standone { get; set; }
        public string surfcondone { get; set; }
        public string markingone { get; set; }
        public string cleaningone { get; set; }
        public string serviceabilityone { get; set; }
        public string standtwo { get; set; }
        public string surfcondtwo { get; set; }
        public string markingtwo { get; set; }
        public string cleaningtwo { get; set; }
        public string serviceabilitytwo { get; set; }
        public string standthree { get; set; }
        public string surfcondthree { get; set; }
        public string markingthree { get; set; }
        public string cleaningthree { get; set; }
        public string serviceabilitythree { get; set; }
        public string standfour { get; set; }
        public string surfcondfour { get; set; }
        public string markingfour { get; set; }
        public string cleaningfour { get; set; }
        public string serviceabilityfour { get; set; }
        public string standfive { get; set; }
        public string surfcondfive { get; set; }
        public string markingfive { get; set; }
        public string cleaningfive { get; set; }
        public string serviceabilityfive { get; set; }
        public string standsix { get; set; }
        public string surfcondsix { get; set; }
        public string markingsix { get; set; }
        public string cleaningsix { get; set; }
        public string serviceabilitysix { get; set; }
        public string standseven { get; set; }
        public string surfcondseven { get; set; }
        public string markingseven { get; set; }
        public string cleaningseven { get; set; }
        public string serviceabilityseven { get; set; }
        public string standeigth { get; set; }
        public string surfcondeigth { get; set; }
        public string markingeigth { get; set; }
        public string cleaningeigth { get; set; }
        public string serviceabilityeigth { get; set; }
        public string standnine { get; set; }
        public string surfcondnine { get; set; }
        public string markingnine { get; set; }
        public string cleaningnine { get; set; }
        public string serviceabilitynine { get; set; }
        public string standten { get; set; }
        public string surfcondten { get; set; }
        public string markingten { get; set; }
        public string cleaningten { get; set; }
        public string serviceabilityten { get; set; }
        public string standeleven { get; set; }
        public string surfcondeleven { get; set; }
        public string markingeleven { get; set; }
        public string cleaningeleven { get; set; }
        public string serviceabilityeleven { get; set; }
        public string standtwelve { get; set; }
        public string surfcondtwelve { get; set; }
        public string markingtwelve { get; set; }
        public string cleaningtwelve { get; set; }
        public string serviceabilitytwelve { get; set; }
        public string standthirteen { get; set; }
        public string surfcondthirteen { get; set; }
        public string markingthirteen { get; set; }
        public string cleaningthirteen { get; set; }
        public string serviceabilitythirteen { get; set; }
        public string standfourteen { get; set; }
        public string surfcondfourteen { get; set; }
        public string markingfourteen { get; set; }
        public string cleaningfourteen { get; set; }
        public string serviceabilityfourteen { get; set; }
        public string standfifteen { get; set; }
        public string surfcondfifteen { get; set; }
        public string markingfifteen { get; set; }
        public string cleaningfifteen { get; set; }
        public string serviceabilityfifteen { get; set; }
        public string standsixteen { get; set; }
        public string surfcondsixteen { get; set; }
        public string markingsixteen { get; set; }
        public string cleaningsixteen { get; set; }
        public string serviceabilitysixteen { get; set; }
        public string standseventeen { get; set; }
        public string surfcondseventeen { get; set; }
        public string markingseventeen { get; set; }
        public string cleaningseventeen { get; set; }
        public string serviceabilityseventeen { get; set; }
        public string standeighteen { get; set; }
        public string surfcondeighteen { get; set; }
        public string markingeighteen { get; set; }
        public string cleaningeighteen { get; set; }
        public string serviceabilityeighteen { get; set; }
        public string standnineteen { get; set; }
        public string surfcondnineteen { get; set; }
        public string markingnineteen { get; set; }
        public string cleaningnineteen { get; set; }
        public string serviceabilitynineteen { get; set; }
        public string standtwenty { get; set; }
        public string surfcondtwenty { get; set; }
        public string markingtwenty { get; set; }
        public string cleaningtwenty { get; set; }
        public string serviceabilitytwenty { get; set; }
        public string standtwentyone { get; set; }
        public string surfcondtwentyone { get; set; }
        public string markingtwentyone { get; set; }
        public string cleaningtwentyone { get; set; }
        public string serviceabilitytwentyone { get; set; }
        public string standtwentytwo { get; set; }
        public string surfcondtwentytwo { get; set; }
        public string markingtwentytwo { get; set; }
        public string cleaningtwentytwo { get; set; }
        public string serviceabilitytwentytwo { get; set; }
        public string standtwentythree { get; set; }
        public string surfcondtwentythree { get; set; }
        public string markingtwentythree { get; set; }
        public string cleaningtwentythree { get; set; }
        public string serviceabilitytwentythree { get; set; }
        public string safetyofficiername { get; set; }
        public string otherobservations { get; set; }
        public string actiontakenone { get; set; }
        public string actiontakentwo { get; set; }
        public string actiontakenthree { get; set; }
        public string actiontakenfour { get; set; }
        public string actiontakenfive { get; set; }
        public string actiontakensix { get; set; }
        public string actiontakenseven { get; set; }
        public string actiontakeneigth { get; set; }
        public string actiontakennine { get; set; }
        public string actiontakenten { get; set; }
        public string actiontakeneleven { get; set; }
        public string actiontakentwelve { get; set; }
        public string actiontakenthirteen { get; set; }
        public string actiontakenfourteen { get; set; }
        public string actiontakenfifteen { get; set; }
        public string actiontakensixteen { get; set; }
        public string actiontakenseventeen { get; set; }
        public string actiontakeneighteen { get; set; }
        public string actiontakennineteen { get; set; }
        public string actiontakentwenty { get; set; }
        public string actiontakentwentyone { get; set; }
        public string actiontakentwentytwo { get; set; }
        public string actiontakentwentythree { get; set; }
    }
}